apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: vcluster-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/sh", "-c"]
        args:
          - echo "hello from namespace $NAMESPACE" > /usr/share/nginx/html/index.html &&
            nginx -g 'daemon off;'
        ports:
        - containerPort: 80